# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    # Install the required libraries
    #   https://platformio.org/lib/show/794/xxtea-lib
    #   https://platformio.org/lib/show/89/PubSubClient
    #   https://platformio.org/lib/show/2951/GxEPD
    - platformio lib -g install 794 89 2951
    - cp include/wifiConfig.tmpl include/wifiConfig.h

script:
    - platformio run